### PR TITLE
toysh is influenced off bash, not busybox ash

### PR DESCRIPTION
**Pull request by iriswebb**
Note: Toybox shell (toysh) attempts to be a bug-for-bug compatible version of bash. Both busybox ash and toysh are meant to be posix compliment, but the feature-set of toysh draws much more influence from bash than anywhere else

### CODE REVIEW

**Comment by marcpaq** [comment]
Hey @oliverkwebb . Thanks for the PR.

Do you have a citation for this info?

**Comment by iriswebb** [comment]
On Mon, Nov 18, 2024 at 11:10, Marc Paquette ***@***.***(mailto:On Mon, Nov 18, 2024 at 11:10, Marc Paquette <<a href=)> wrote:

> Hey ***@***.***(https://github.com/oliverkwebb) . Thanks for the PR.
>
> Do you have a citation for this info?

The roadmap page for toybox (http://landley.net/toybox/roadmap.html) says:

"Finally, we'd like to provide a good replacement for the Bash shell"

And a talk given but the creator of toybox (at 45:25):
https://youtu.be/SGmtP5Lg_t0

**Review by marcpaq — APPROVED** [review]
Nice work. Thanks!

**Comment by marcpaq** [comment]
Hey @oliverkwebb 

Just a heads up: I've merged your correction, but I've kept the dotted line to BusyBox. 

Rationale: One of Robert Landley's early goals for toybox was to provide a GPL-less BusyBox for Android. And, as you pointed out, he also wants toybox to be a decent Bash replacement.

Let me know what you think.

**Pull request merged**
